version: '3.8' 
services:
  mongo:
    image: mongo:latest 
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db 

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  backend:
    build: .
    container_name: picturethis-backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/picturethis?authSource=admin
      MONGODB_DATABASE: picturethis
      JWT_SECRET: WTkM+X9O4Vn7kDjZgEy3kJxJHTe+qJ7VcPqHF9p+DcY=
    depends_on:
      - mongo
      - mongo-express

volumes:
  mongo_data:
